/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/global/input/LInputField copy.vue')['default']
    LButton: typeof import('./src/components/global/input/LButton.vue')['default']
    LCard: typeof import('./src/components/global/structure/LCard.vue')['default']
    LFieldset: typeof import('./src/components/global/structure/LFieldset.vue')['default']
    LFieldSet: typeof import('./src/components/global/structure/LFieldSet.vue')['default']
    LForm: typeof import('./src/components/global/structure/LForm.vue')['default']
    LGrid: typeof import('./src/components/global/structure/LGrid.vue')['default']
    LInput: typeof import('./src/components/global/input/LInput.vue')['default']
    LInputField: typeof import('./src/components/global/input/LInputField.vue')['default']
    LInputRepeater: typeof import('./src/components/global/input/LInputRepeater.vue')['default']
    LList: typeof import('./src/components/global/structure/LList.vue')['default']
    LMapEntry: typeof import('./src/components/global/input/LMapEntry.vue')['default']
    LModal: typeof import('./src/components/global/LModal.vue')['default']
    LPage: typeof import('./src/components/global/structure/LPage.vue')['default']
    LSelectField: typeof import('./src/components/global/input/LSelectField.vue')['default']
    LTable: typeof import('./src/components/global/structure/LTable.vue')['default']
    LWizard: typeof import('./src/components/global/structure/LWizard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/global/structure/TheHeader.vue')['default']
  }
}
