// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiFlightPlansData, GetApiFlightPlansResponses, GetApiMissionsData, GetApiMissionsResponses, PostApiFlightPlansData, PostApiFlightPlansResponses, PostApiMissionsData, PostApiMissionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiFlightPlans = <ThrowOnError extends boolean = false>(options?: Options<GetApiFlightPlansData, ThrowOnError>): RequestResult<GetApiFlightPlansResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiFlightPlansResponses, unknown, ThrowOnError>({ url: '/api/flight-plans', ...options });

export const postApiFlightPlans = <ThrowOnError extends boolean = false>(options: Options<PostApiFlightPlansData, ThrowOnError>): RequestResult<PostApiFlightPlansResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiFlightPlansResponses, unknown, ThrowOnError>({
    url: '/api/flight-plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiMissions = <ThrowOnError extends boolean = false>(options?: Options<GetApiMissionsData, ThrowOnError>): RequestResult<GetApiMissionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMissionsResponses, unknown, ThrowOnError>({ url: '/api/missions', ...options });

export const postApiMissions = <ThrowOnError extends boolean = false>(options: Options<PostApiMissionsData, ThrowOnError>): RequestResult<PostApiMissionsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiMissionsResponses, unknown, ThrowOnError>({
    url: '/api/missions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
