// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type FlightPlanDto = {
    /**
     * The ID of the Flight Plan.
     */
    id: string;
    /**
     * The name of the Flight Plan.
     */
    name: string;
    /**
     * The GitHub workflow branch targeted by the Flight Plan.
     */
    workflowBranch: string;
    /**
     * The GitHub environment targeted by the Flight Plan.
     */
    environment: string;
    /**
     * The services targeted by the Flight Plan.
     */
    services: Array<string>;
    /**
     * The Phases of the Flight Plan.
     */
    phases: Array<{
        id: string;
        status: 'DRAFT' | 'WAITING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
        execution: 'PARALLEL' | 'SEQUENTIAL';
        steps: Array<{
            id: string;
            repository: string;
            workflowId: string;
            workflowOutcome: 'DRAFT' | 'WAITING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
            exposedWorkflowInputs: {
                [key: string]: unknown;
            };
            workflowInputs: {
                [key: string]: unknown;
            };
            createdAt: string;
            lastUpdatedAt: string;
            startedAt: string;
            completedAt: string;
        }>;
        createdAt: string;
        lastUpdatedAt: string;
        startedAt: string;
        completedAt: string;
    }>;
    /**
     * The creation date of the Flight Plan.
     */
    createdAt: string;
    /**
     * The date of the last update of the Flight Plan.
     */
    lastUpdatedAt: string;
};

export type MissionDto = {
    /**
     * The ID of the Mission.
     */
    id: string;
    /**
     * The correlation ID of the Mission.
     */
    correlationId: string;
    /**
     * The Flight Plan ID of the Mission.
     */
    flightPlanId: string;
    /**
     * The targeted GitHub workflow branch of the Mission.
     */
    workflowBranch: string;
    /**
     * The targeted GitHub environment of the Mission.
     */
    environment: string;
    /**
     * The targeted services of the Mission.
     */
    services: Array<string>;
    /**
     * The director of the Mission.
     */
    director: string;
    /**
     * The status of the Mission.
     */
    status: 'DRAFT' | 'LAUNCHING' | 'IN-ORBIT' | 'LANDED' | 'ABORTED';
    /**
     * The Phases of the Mission.
     */
    phases: Array<{
        id: string;
        status: 'DRAFT' | 'WAITING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
        execution: 'PARALLEL' | 'SEQUENTIAL';
        steps: Array<{
            id: string;
            repository: string;
            workflowId: string;
            workflowOutcome: 'DRAFT' | 'WAITING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
            exposedWorkflowInputs: {
                [key: string]: unknown;
            };
            workflowInputs: {
                [key: string]: unknown;
            };
            createdAt: string;
            lastUpdatedAt: string;
            startedAt: string;
            completedAt: string;
        }>;
        createdAt: string;
        lastUpdatedAt: string;
        startedAt: string;
        completedAt: string;
    }>;
    /**
     * The creation date of the Mission.
     */
    createdAt: string;
    /**
     * The date of the last update of the Mission.
     */
    lastUpdatedAt: string;
    /**
     * The launch date of the Mission.
     */
    launchedAt: string;
    /**
     * The date of completion of the Mission.
     */
    completedAt: string;
};

export type GetApiFlightPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/flight-plans';
};

export type GetApiFlightPlansResponses = {
    /**
     * Return all existing Flight Plans.
     */
    200: Array<FlightPlanDto>;
};

export type GetApiFlightPlansResponse = GetApiFlightPlansResponses[keyof GetApiFlightPlansResponses];

export type PostApiFlightPlansData = {
    body: {
        /**
         * The name of the Flight Plan to create.
         */
        name: string;
        /**
         * The GitHub workflow branch of the Flight Plan to create.
         */
        workflowBranch: string;
        /**
         * The targeted GitHub environment of the Flight Plan to create.
         */
        environment: string;
        /**
         * The targeted services of the Flight Plan to create.
         */
        services: Array<string>;
        /**
         * The Phases to create for the Flight Plan to create.
         */
        phases: Array<{
            /**
             * The execution method of the Phase to create.
             */
            execution: 'PARALLEL' | 'SEQUENTIAL';
            /**
             * The Steps to create for the Phase to create.
             */
            steps: Array<{
                /**
                 * The targeted GitHub repository of the Step to create.
                 */
                repository: string;
                /**
                 * The targeted GitHub workflow ID of the Step to create.
                 */
                workflowId: string;
                /**
                 * The exposed inputs of the targeted GitHub workflow of the Step to create.
                 */
                exposedWorkflowInputs?: {
                    [key: string]: unknown;
                };
                /**
                 * All inputs of the targeted GitHub workflow of the Step to create.
                 */
                workflowInputs?: {
                    [key: string]: unknown;
                };
            }>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/flight-plans';
};

export type PostApiFlightPlansResponses = {
    /**
     * Return the newly created Flight Plan.
     */
    200: FlightPlanDto;
};

export type PostApiFlightPlansResponse = PostApiFlightPlansResponses[keyof PostApiFlightPlansResponses];

export type GetApiMissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/missions';
};

export type GetApiMissionsResponses = {
    /**
     * Return all existing Missions.
     */
    200: Array<MissionDto>;
};

export type GetApiMissionsResponse = GetApiMissionsResponses[keyof GetApiMissionsResponses];

export type PostApiMissionsData = {
    body: {
        /**
         * The targeted GitHub workflow branch of the Mission to create.
         */
        workflowBranch: string;
        /**
         * The targeted GitHub environment of the Mission to create.
         */
        environment: string;
        /**
         * The targeted services of the Mission to create.
         */
        services: Array<string>;
        /**
         * The name of the director of the Mission to create.
         */
        director: string;
        /**
         * The Phases to create for the Flight Plan to create.
         */
        phases: Array<{
            /**
             * The execution method of the Phase to create.
             */
            execution: 'PARALLEL' | 'SEQUENTIAL';
            /**
             * The Steps to create for the Phase to create.
             */
            steps: Array<{
                /**
                 * The targeted GitHub repository of the Step to create.
                 */
                repository: string;
                /**
                 * The targeted GitHub workflow ID of the Step to create.
                 */
                workflowId: string;
                /**
                 * The exposed inputs of the targeted GitHub workflow of the Step to create.
                 */
                exposedWorkflowInputs?: {
                    [key: string]: unknown;
                };
                /**
                 * All inputs of the targeted GitHub workflow of the Step to create.
                 */
                workflowInputs?: {
                    [key: string]: unknown;
                };
            }>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/missions';
};

export type PostApiMissionsResponses = {
    /**
     * Return the newly created Mission.
     */
    200: MissionDto;
};

export type PostApiMissionsResponse = PostApiMissionsResponses[keyof PostApiMissionsResponses];
